version: '0.1'

services:
  prediction-api:
    build:
      context: prediction-api
    container_name: prediction-api
    user: root
    ports:
      - "5001:5000"
    networks:
      - network-a
      - network-b
    environment:
      - MODEL_REPO=/usr/src/myapp/models
    volumes:
      - "/home/p_a_haupt/models:/usr/src/myapp/models"
  prediction-ui:
    build:
      context: prediction-ui
    container_name: prediction-ui
    user: root
    depends_on:
      - prediction-api
    ports:
      - "5000:5000"
    networks:
      - network-a
    environment:
      - MODEL_REPO=/usr/src/myapp/models
    volumes:
      - "/home/p_a_haupt/models:/usr/src/myapp/models"
  training-api:
    build:
      context: training-api
    container_name: training-api
    depends_on:
      - prediction-api
    user: root
    ports:
      - "5001:5000"
    networks:
      - network-b
    environment:
      - MODEL_REPO=/usr/src/myapp/models
    volumes:
      - "/home/p_a_haupt/models:/usr/src/myapp/models"
networks:
  network-a:
  network-b:
    



